/**
 * HelixBench question banks — BioPython & pharma computational biology
 * for AI drug discovery interview prep.
 */
const LEVELS = [
  {
    id: "foundation",
    name: "Foundation",
    meta: "Sequence I/O · SMILES literacy · BioPython basics",
    desc: "Entry-level CompBio Python: FASTA/PDB handling, Seq objects, cheminformatics vocabulary, and assay table hygiene.",
  },
  {
    id: "practitioner",
    name: "Practitioner",
    meta: "RDKit · pipelines · QSAR features",
    desc: "Day-to-day discovery workflows: fingerprints, ChEMBL-style data, Bio.Align, pandas assay joins, and ADMET filters.",
  },
  {
    id: "specialist",
    name: "Specialist",
    meta: "Molecular ML · GNNs · production CompBio",
    desc: "Senior bar: graph models, generative chemistry, multi-omics integration, docking post-processing, and scalable pipelines.",
  },
];

const QUESTIONS = {
  foundation: [
    {
      topic: "BioPython · SeqIO",
      question: "In a target ID campaign you receive a multi-FASTA of candidate genes. Which BioPython call correctly iterates SeqRecord objects from a FASTA file?",
      code: "from Bio import SeqIO",
      choices: [
        "SeqIO.parse('targets.fasta', 'fasta')",
        "SeqIO.read_all('targets.fasta')",
        "SeqIO.load('targets.fasta', format='fa')",
        "SeqIO.open_fasta('targets.fasta').records()",
      ],
      answer: 0,
      explanation: "SeqIO.parse(handle, format) yields SeqRecord objects one-by-one — the standard pattern for multi-record FASTA in discovery pipelines.",
    },
    {
      topic: "BioPython · Seq",
      question: "You need the reverse complement of a CDS before translating an off-target transcript. What does Bio.Seq provide?",
      code: "from Bio.Seq import Seq\ncds = Seq('ATGCGT')",
      choices: [
        "cds.reverse_complement()",
        "cds.complement().reverse()",
        "SeqOps.rc(cds)",
        "cds[::-1].transcribe()",
      ],
      answer: 0,
      explanation: "Seq.reverse_complement() returns the reverse-complemented sequence — essential before translating antisense or reverse-strand features.",
    },
    {
      topic: "Cheminformatics · SMILES",
      question: "In a hit-list export from a virtual screen, what does a SMILES string primarily encode?",
      choices: [
        "A linear text representation of a molecular graph (atoms & bonds)",
        "A 3D conformer coordinate dump",
        "A protein secondary-structure string",
        "A hashed binary fingerprint only",
      ],
      answer: 0,
      explanation: "SMILES encodes atoms and bonds as text. 3D coords need SDF/MOL2; fingerprints are derived descriptors, not SMILES itself.",
    },
    {
      topic: "BioPython · translation",
      question: "Translating a coding sequence for an antibody Fv domain, which call yields an amino-acid Seq?",
      code: "from Bio.Seq import Seq\ncds = Seq('ATGGAAGTGCAG...')",
      choices: [
        "cds.translate()",
        "cds.transcribe().protein()",
        "SeqIO.translate(cds)",
        "cds.to_protein(table=1)",
      ],
      answer: 0,
      explanation: "Seq.translate() maps DNA/RNA codons to amino acids (optional codon table). Transcription alone does not produce protein.",
    },
    {
      topic: "Assay data · pandas",
      question: "An HTS plate map CSV has columns compound_id, well, and IC50_nM. Which pandas pattern best loads it for QC?",
      choices: [
        "pd.read_csv('plate.csv') then filter/astype numeric IC50",
        "open('plate.csv').readlines() and split on commas only",
        "np.loadtxt('plate.csv') ignoring headers",
        "json.load(open('plate.csv'))",
      ],
      answer: 0,
      explanation: "pd.read_csv handles headers, mixed types, and missing wells. IC50 should be coerced numeric before thresholding actives.",
    },
    {
      topic: "Structures · PDB",
      question: "You download a kinase co-crystal for pose inspection. Which BioPython module parses PDB coordinate records?",
      choices: [
        "Bio.PDB",
        "Bio.StructureIO",
        "Bio.Align.PDB",
        "Bio.SeqIO with format='pdb'",
      ],
      answer: 0,
      explanation: "Bio.PDB (PDBParser / MMCIFParser) builds Structure→Model→Chain→Residue→Atom hierarchies for structural biology work.",
    },
    {
      topic: "Identifiers · InChIKey",
      question: "Why do compound registries often store InChIKey alongside SMILES in pharma warehouses?",
      choices: [
        "InChIKey is a fixed-length hash-like key useful for deduplication across tautomer/SMILES variants",
        "InChIKey stores 3D docking poses",
        "InChIKey replaces the need for any structural format",
        "InChIKey is only valid for peptides",
      ],
      answer: 0,
      explanation: "InChIKey provides a compact, standardized lookup key. Canonical SMILES still varies by toolkit; InChI/InChIKey improve identity matching.",
    },
    {
      topic: "BioPython · GC content",
      question: "For oligo design around a CRISPR cut site, which Bio.SeqUtils helper computes GC fraction?",
      choices: [
        "GC(sequence) from Bio.SeqUtils",
        "Seq.gc_ratio()",
        "Align.gc_content()",
        "Entrez.gc()",
      ],
      answer: 0,
      explanation: "Bio.SeqUtils.gc_fraction (historically GC) is the standard helper for GC content on Seq or string inputs.",
    },
    {
      topic: "Formats · SDF",
      question: "A vendor library arrives as multi-molecule SDF. What does each molfile block typically contain?",
      choices: [
        "Connection table (atoms/bonds) plus optional properties like vendor ID or MW",
        "Only protein FASTA headers",
        "RNA-seq count matrices",
        "BLAST pairwise alignments",
      ],
      answer: 0,
      explanation: "SDF concatenates molfiles with optional SD tags — the workhorse format for small-molecule libraries in discovery.",
    },
    {
      topic: "BioPython · SeqRecord",
      question: "When writing annotated transcripts back to FASTA, which attribute holds the sequence ID used in the header?",
      choices: [
        "record.id",
        "record.handle",
        "record.locus_tag only",
        "record.dbxrefs[0] always",
      ],
      answer: 0,
      explanation: "SeqRecord.id populates the FASTA header token. description can hold the remainder; annotations live in .annotations / .features.",
    },
    {
      topic: "Units · potency",
      question: "An assay table lists pIC50 = 7.0. Approximately what IC50 does that correspond to?",
      choices: [
        "100 nM (IC50 = 10^(-pIC50) M)",
        "7 μM exactly",
        "0.7 M",
        "70 mM",
      ],
      answer: 0,
      explanation: "pIC50 = −log10(IC50[M]). pIC50 7 ⇒ 10⁻⁷ M = 100 nM — common potency reporting in SAR tables.",
    },
    {
      topic: "BioPython · Entrez",
      question: "Pulling a RefSeq nucleotide for a disease gene via NCBI, which BioPython submodule wraps Entrez eUtils?",
      choices: [
        "Bio.Entrez",
        "Bio.GenBank.HTTP",
        "Bio.DB.NCBI",
        "Bio.SeqIO.Entrez",
      ],
      answer: 0,
      explanation: "Bio.Entrez provides efetch/esearch with email/tool etiquette required for programmatic NCBI access.",
    },
  ],

  practitioner: [
    {
      topic: "RDKit · molecules",
      question: "In a triage notebook, which RDKit call parses a SMILES into a molecule object for descriptor calc?",
      code: "from rdkit import Chem",
      choices: [
        "Chem.MolFromSmiles(smi)",
        "Chem.ParseSMILES(smi)",
        "Chem.SmilesToMol(smi)",
        "Chem.ReadSmiles(smi)",
      ],
      answer: 0,
      explanation: "Chem.MolFromSmiles is the canonical constructor; it returns None on invalid SMILES — always null-check in pipelines.",
    },
    {
      topic: "RDKit · fingerprints",
      question: "For a Tanimoto nearest-neighbor search on a corporate compound collection, which fingerprint is a common default?",
      choices: [
        "Morgan (ECFP-like) fingerprints via AllChem.GetMorganFingerprintAsBitVect",
        "Only raw SMILES string distance",
        "PWM matrices from Bio.motifs",
        "FASTA k-mer counts",
      ],
      answer: 0,
      explanation: "Morgan/ECFP bit vectors plus Tanimoto similarity are the workhorse for ligand-based neighbor finding in medchem.",
    },
    {
      topic: "BioPython · Align",
      question: "You align ortholog catalytic sites before homology modeling. Which Bio.Align approach fits pairwise protein alignment?",
      choices: [
        "PairwiseAligner with a protein substitution matrix (e.g. BLOSUM62)",
        "SeqIO.align() with format='clustal'",
        "Entrez.align_blast_only",
        "PDBParser.align_chains()",
      ],
      answer: 0,
      explanation: "Bio.Align.PairwiseAligner (replacing deprecated pairwise2) supports protein matrices for ortholog comparisons.",
    },
    {
      topic: "ChEMBL-style data",
      question: "Joining bioactivity to structures, you see standard_type = 'IC50' and standard_units = 'nM'. What should you do before QSAR?",
      choices: [
        "Harmonize units, handle censored/qualified values, and deduplicate by parent compound",
        "Train directly on mixed M and nM without conversion",
        "Drop all IC50 and keep only %inhibition at one conc",
        "Convert IC50 to SMILES length as the label",
      ],
      answer: 0,
      explanation: "Activity curation — unit conversion, qualifier handling (>, <), salt/parent mapping — dominates real ChEMBL-derived QSAR quality.",
    },
    {
      topic: "ADMET filters",
      question: "Applying a Lipinski-inspired filter in RDKit, which property set is most associated with oral drug-likeness rules of thumb?",
      choices: [
        "MW, LogP, H-bond donors/acceptors (and often rotatable bonds)",
        "Only melting point and color",
        "FASTA length and GC%",
        "BLAST e-value only",
      ],
      answer: 0,
      explanation: "Ro5-style filters use MW, LogP, HBD/HBA (Veber adds TPSA/rotors). They are heuristics, not hard go/no-go in modern discovery.",
    },
    {
      topic: "Assay pipelines",
      question: "Plate-based IC50 curves are fit per compound. Which practice avoids leaking future dose points into a potency model?",
      choices: [
        "Split by compound scaffold/series (or time) so all concentrations of a molecule stay in one fold",
        "Randomly shuffle every well row independently into train/test",
        "Put all high-dose wells in train and low-dose in test",
        "Use the same compounds in train and test if doses differ",
      ],
      answer: 0,
      explanation: "Group-aware splits (scaffold / Bemis–Murcko / temporal) prevent over-optimistic QSAR from near-duplicate chemotypes.",
    },
    {
      topic: "Bio.PDB · neighbors",
      question: "Measuring ligand–pocket contacts, which Bio.PDB pattern finds atoms within a distance cutoff?",
      choices: [
        "NeighborSearch(atom_list).search(center, radius)",
        "PDBParser.nearby(ligand, 5)",
        "SeqIO.proximity()",
        "Align.Structure.contacts()",
      ],
      answer: 0,
      explanation: "Bio.PDB.NeighborSearch builds a KD-tree over atoms for efficient spatial queries around ligands or residues.",
    },
    {
      topic: "Descriptors · QSAR",
      question: "You engineer features for a random-forest pIC50 model. Which set is typical for classical ligand-based QSAR?",
      choices: [
        "Physicochemical descriptors + fingerprints (e.g. Morgan bits, LogP, TPSA, MW)",
        "Only raw PDB ATOM lines as strings",
        "RNA-seq TPM vectors for the ligand",
        "Keyboard scan codes of the SMILES characters",
      ],
      answer: 0,
      explanation: "Classical QSAR combines continuous descriptors with binary fingerprints; structure-based models may add pocket features separately.",
    },
    {
      topic: "RDKit · sanitization",
      question: "MolFromSmiles returns a molecule but later descriptor calc fails. What is a common root cause?",
      choices: [
        "Failed or incomplete sanitization / valence issues; need sanitization checks or MolFromSmiles(..., sanitize=True) handling",
        "SMILES are never usable in RDKit",
        "You must convert SMILES to FASTA first",
        "RDKit only reads InChIKey",
      ],
      answer: 0,
      explanation: "Sanitization enforces valence and aromaticity. Broken vendor SMILES often need cleanup (e.g. SanitizeMol, salt stripping).",
    },
    {
      topic: "Multi-sequence · MSA",
      question: "Building an MSA of related proteases for conservation mapping, which format does BioPython commonly write/read?",
      choices: [
        "Clustal / Stockholm / FASTA alignments via AlignIO",
        "Only JPEG screenshots of Jalview",
        "SDF supplier catalogs",
        "CSV well maps",
      ],
      answer: 0,
      explanation: "Bio.AlignIO handles MSA formats (Clustal, Stockholm, phylip, fasta) used downstream of MAFFT/Clustal Omega.",
    },
    {
      topic: "Target engagement",
      question: "You merge cellular IC50 with biochemical Ki. Why can naive pooling mislead a potency model?",
      choices: [
        "Different assay modalities, protein forms, and conditions are not commensurate without careful normalization",
        "Ki and IC50 are always identical by definition",
        "Cellular assays never use nM units",
        "Biochemical assays cannot be stored in pandas",
      ],
      answer: 0,
      explanation: "Cross-assay pooling needs metadata-aware modeling; Cheng–Prusoff and cell permeability confound direct IC50↔Ki merges.",
    },
    {
      topic: "Substructure filters",
      question: "Flagging PAINS-like alerts on a hit list in RDKit is typically done with:",
      choices: [
        "SMARTS-based structural filters (e.g. FilterCatalog / custom SMARTS)",
        "BLASTP against UniProt",
        "GC content thresholds",
        "Entrez taxonomy IDs",
      ],
      answer: 0,
      explanation: "Substructure alerts use SMARTS patterns. They are triage aids — not definitive proof of assay interference.",
    },
  ],

  specialist: [
    {
      topic: "Molecular graphs · GNNs",
      question: "In a graph neural net for binding prediction, what are the natural node and edge features?",
      choices: [
        "Atoms as nodes (element, charge, hybridization…) and bonds as edges (order, conjugation…)",
        "SMILES characters as CNN tokens only — graphs are unused",
        "PDB residue indices as SMILES nodes",
        "Plate well IDs as graph edges",
      ],
      answer: 0,
      explanation: "Message-passing GNNs operate on molecular graphs: atom nodes and bond edges, optionally with 3D distances for spatial models.",
    },
    {
      topic: "Train/test leakage",
      question: "Your GNN hits 0.98 AUROC on a random split of ChEMBL kinase IC50s but fails prospectively. Most likely cause?",
      choices: [
        "Analogue / scaffold leakage — chemically similar molecules in both splits inflate metrics",
        "AUROC cannot be used for potency tasks ever",
        "RDKit fingerprints are incompatible with neural nets",
        "Too much protein sequence data was included",
      ],
      answer: 0,
      explanation: "Scaffold and time splits expose generalization; random splits leak close analogues and overstate discovery performance.",
    },
    {
      topic: "Generative chemistry",
      question: "A SMILES VAE proposes invalid strings. Which mitigation is most appropriate in production ideation?",
      choices: [
        "Use grammar/atom-aware decoders or graph generators, plus RDKit validity & property filters post hoc",
        "Accept all outputs and skip chemistry checks",
        "Convert invalid SMILES to protein FASTA",
        "Train only on InChIKey characters",
      ],
      answer: 0,
      explanation: "Validity constraints (syntax models, graph decoders) plus chemistry filters (valence, PAINS, property windows) are standard.",
    },
    {
      topic: "Docking post-processing",
      question: "After a large docking campaign, scores alone rank poorly vs experiment. A robust Python triage often includes:",
      choices: [
        "Pose clustering, interaction fingerprints, rescoring/ML, and visual/pharmacophore filters",
        "Sorting solely by alphabetical ligand name",
        "Keeping only the worst energy pose",
        "Converting poses to RNA-seq counts",
      ],
      answer: 0,
      explanation: "Docking enrichment improves with consensus rescoring, IFPs, and human-in-the-loop pose QC — not raw score alone.",
    },
    {
      topic: "Multi-omics · targets",
      question: "Prioritizing targets for an AI-first portfolio, which integration is most coherent?",
      choices: [
        "Genetics/omics evidence + tractability (structure, assays) + competitive landscape features in one ranked model",
        "Only social media mentions of the gene symbol",
        "Random genes with the shortest FASTA files",
        "Targets with no human ortholog exclusively",
      ],
      answer: 0,
      explanation: "Target ID combines causal human genetics, expression, safety, and chemical tractability — CompBio engineering stitches these evidence layers.",
    },
    {
      topic: "Uncertainty",
      question: "For active learning on expensive wet-lab assays, what should the acquisition function balance?",
      choices: [
        "Predicted potency / utility vs epistemic uncertainty (explore–exploit)",
        "Only molecules with the longest SMILES",
        "Compounds already measured 10+ times",
        "Random plates without model input",
      ],
      answer: 0,
      explanation: "Bayesian / ensemble uncertainty guides which compounds to synthesize or assay next under budget constraints.",
    },
    {
      topic: "Protein language models",
      question: "Embedding a target sequence with a protein LM (e.g. ESM-style) for druggability features — what is a valid use?",
      choices: [
        "Sequence embeddings as features for variant effect, binding, or tractability models alongside structure cues",
        "Replacing all chemical structures with DNA barcodes only",
        "Generating valid small-molecule SMILES directly from DNA codons without a decoder",
        "Computing Tanimoto similarity between proteins",
      ],
      answer: 0,
      explanation: "pLMs yield contextual sequence embeddings used in variant effect and multimodal target/ligand models — not SMILES generators by themselves.",
    },
    {
      topic: "Scalable pipelines",
      question: "Nightly recompute of 5M fingerprints + NN search. Which design is most production-appropriate?",
      choices: [
        "Chunked RDKit featurization, vectorized similarity (or ANN index), idempotent artifact stores, and lineage metadata",
        "One giant notebook cell with everything in global RAM and no versions",
        "Manual copy-paste of CSV emails",
        "Re-parse PDB for every fingerprint",
      ],
      answer: 0,
      explanation: "Production CompBio uses batched featurization, approximate NN indexes, caching, and data lineage for regulated environments.",
    },
    {
      topic: "Conformal / calibration",
      question: "Medicinal chemists ask for prediction intervals on pIC50. What is a sound approach?",
      choices: [
        "Calibrated uncertainty (e.g. ensembles, conformal prediction) validated on scaffold-held-out series",
        "Always report ±0.01 regardless of domain",
        "Hide errors when confidence is low",
        "Use training RMSE as the interval for every new chemotype",
      ],
      answer: 0,
      explanation: "Well-calibrated uncertainties — especially under scaffold shift — are more decision-useful than point estimates alone.",
    },
    {
      topic: "3D / conformers",
      question: "For shape or pharmacophore screening in Python, which RDKit capability is commonly used first?",
      choices: [
        "EmbedMolecule / ETKDG conformer generation then align or shape overlay",
        "Seq.translate on the SMILES string",
        "Entrez.efetch of conformers",
        "FASTA MSA of ligands",
      ],
      answer: 0,
      explanation: "ETKDG conformer generation underpins 3D descriptors, shape sims, and pharmacophore workflows before heavier MD/docking.",
    },
    {
      topic: "Federated / privacy",
      question: "Two pharma partners want to train a shared ADMET model without sharing structures. A CompBio-aware option is:",
      choices: [
        "Federated learning or sharing only fingerprints/embeddings under a legal data contract — never raw IP SMILES by default",
        "Emailing full SDF libraries to a public GitHub gist",
        "Publishing all series in a blog post",
        "Training only on public caffeine SMILES",
      ],
      answer: 0,
      explanation: "IP-sensitive structures drive federated or feature-level collaboration patterns with strict governance.",
    },
    {
      topic: "Multimodal fusion",
      question: "A complex model fuses ligand graphs, pocket voxels, and assay metadata. What failure mode should you test first?",
      choices: [
        "Modality dropout / missing pocket structures and assay-type shift — ensure graceful degradation",
        "Whether the GPU brand matches the laptop sticker",
        "If FASTA headers contain emoji",
        "Sorting SMILES alphabetically before every epoch only",
      ],
      answer: 0,
      explanation: "Real discovery data is incomplete: apo structures, missing assays, new target families. Robust fusion handles missing modalities.",
    },
  ],
};

const SESSION_SIZE = 10;
