/**
 * HelixBench question banks — BioPython & pharma computational biology
 * for AI drug discovery interview prep.
 * Organized by scientific domain. Correct answers may sit at any index;
 * the app shuffles choices (and questions) each session.
 */
const DOMAINS = [
  {
    id: "genomics",
    name: "Genomics",
    meta: "SeqIO · Entrez · MSA · CRISPR oligos",
    desc: "Sequence I/O, reverse complement, GC content, NCBI Entrez, and multi-sequence alignments for target ID.",
  },
  {
    id: "chemistry",
    name: "Chemistry",
    meta: "SMILES · RDKit · fingerprints · QSAR",
    desc: "Small-molecule representation, descriptors, similarity search, ADMET filters, and activity curation.",
  },
  {
    id: "molecular",
    name: "Molecular",
    meta: "PDB · pockets · protein LMs · targets",
    desc: "Structure hierarchies, pocket contacts, sequence embeddings, and multimodal target prioritization.",
  },
  {
    id: "biologics",
    name: "Biologics",
    meta: "Antibodies · translation · orthologs",
    desc: "Protein sequences, antibody Fv translation, pairwise alignment, and biologics-oriented BioPython workflows.",
  },
  {
    id: "docking",
    name: "Docking",
    meta: "Poses · IFPs · conformers · rescoring",
    desc: "Virtual screening triage, pose clustering, 3D conformers, and structure-based neighbor search.",
  },
  {
    id: "clinical",
    name: "Clinical",
    meta: "Assays · potency · splits · uncertainty",
    desc: "HTS tables, pIC50, cross-assay pooling, scaffold splits, active learning, and decision-ready uncertainty.",
  },
];

const QUESTIONS = {
  genomics: [
    {
      topic: "BioPython · SeqIO",
      question: "In a target ID campaign you receive a multi-FASTA of candidate genes. Which BioPython call correctly iterates SeqRecord objects from a FASTA file?",
      code: "from Bio import SeqIO",
      choices: [
        "SeqIO.parse('targets.fasta', 'fasta')",
        "SeqIO.read_all('targets.fasta')",
        "SeqIO.load('targets.fasta', format='fa')",
        "SeqIO.open_fasta('targets.fasta').records()",
      ],
      answer: 0,
      explanation: "SeqIO.parse(handle, format) yields SeqRecord objects one-by-one — the standard pattern for multi-record FASTA in discovery pipelines.",
    },
    {
      topic: "BioPython · Seq",
      question: "You need the reverse complement of a CDS before translating an off-target transcript. What does Bio.Seq provide?",
      code: "from Bio.Seq import Seq\ncds = Seq('ATGCGT')",
      choices: [
        "cds.reverse_complement()",
        "cds.complement().reverse()",
        "SeqOps.rc(cds)",
        "cds[::-1].transcribe()",
      ],
      answer: 0,
      explanation: "Seq.reverse_complement() returns the reverse-complemented sequence — essential before translating antisense or reverse-strand features.",
    },
    {
      topic: "BioPython · GC content",
      question: "For oligo design around a CRISPR cut site, which Bio.SeqUtils helper computes GC fraction?",
      choices: [
        "gc_fraction(sequence) / historically GC() from Bio.SeqUtils",
        "Seq.gc_ratio()",
        "Align.gc_content()",
        "Entrez.gc()",
      ],
      answer: 0,
      explanation: "Bio.SeqUtils.gc_fraction (historically GC) is the standard helper for GC content on Seq or string inputs.",
    },
    {
      topic: "BioPython · SeqRecord",
      question: "When writing annotated transcripts back to FASTA, which attribute holds the sequence ID used in the header?",
      choices: [
        "record.id",
        "record.handle",
        "record.locus_tag only",
        "record.dbxrefs[0] always",
      ],
      answer: 0,
      explanation: "SeqRecord.id populates the FASTA header token. description can hold the remainder; annotations live in .annotations / .features.",
    },
    {
      topic: "BioPython · Entrez",
      question: "Pulling a RefSeq nucleotide for a disease gene via NCBI, which BioPython submodule wraps Entrez eUtils?",
      choices: [
        "Bio.Entrez",
        "Bio.GenBank.HTTP",
        "Bio.DB.NCBI",
        "Bio.SeqIO.Entrez",
      ],
      answer: 0,
      explanation: "Bio.Entrez provides efetch/esearch with email/tool etiquette required for programmatic NCBI access.",
    },
    {
      topic: "Multi-sequence · MSA",
      question: "Building an MSA of related proteases for conservation mapping, which format does BioPython commonly write/read?",
      choices: [
        "Clustal / Stockholm / FASTA alignments via AlignIO",
        "Only JPEG screenshots of Jalview",
        "SDF supplier catalogs",
        "CSV well maps",
      ],
      answer: 0,
      explanation: "Bio.AlignIO handles MSA formats (Clustal, Stockholm, phylip, fasta) used downstream of MAFFT/Clustal Omega.",
    },
    {
      topic: "Variant annotation",
      question: "You map a coding SNP to protein consequence before a genetics-driven target brief. Which practice is sound?",
      choices: [
        "Use transcript-aware coordinates (e.g. HGVS) and confirm the correct isoform before AA numbering",
        "Always number from genomic contig position as the amino-acid index",
        "Ignore strand because reverse complement never matters for SNPs",
        "Treat every SNP as a frameshift by default",
      ],
      answer: 0,
      explanation: "Isoform choice and strand matter; HGVS-style transcript mapping avoids wrong residue indices in CompBio reports.",
    },
    {
      topic: "RNA-seq counts",
      question: "Joining bulk RNA-seq TPMs to a target list in pandas, what should you verify first?",
      choices: [
        "Gene ID namespace consistency (Ensembl vs Entrez vs symbols) and duplicate symbol collisions",
        "That TPM columns are stored as SMILES strings",
        "That every gene has an identical PDB ligand",
        "That FASTA headers equal plate well IDs",
      ],
      answer: 0,
      explanation: "ID mapping errors dominate omics joins — symbols collide and Ensembl/Entrez versions drift across releases.",
    },
    {
      topic: "Genome browsers · intervals",
      question: "Intersecting ChIP peaks with gene promoters in Python is typically done with:",
      choices: [
        "Interval trees / bedtools-like libraries (e.g. pybedtools, pyranges) on genomic coordinates",
        "Tanimoto similarity on peak FASTA only",
        "RDKit MolFromSmiles on chromosome names",
        "SeqIO.translate of BED files",
      ],
      answer: 0,
      explanation: "Genomic interval algebra (BED/GFF) is the right abstraction — not cheminformatics fingerprints.",
    },
    {
      topic: "Off-target search",
      question: "Screening guide RNA off-targets against a reference genome in a CompBio pipeline usually relies on:",
      choices: [
        "Fast approximate aligners / dedicated CRISPR off-target tools, then ranked mismatch reports",
        "Random Forest on SMILES of the guide alone",
        "Lipinski filters on the guide RNA",
        "Docking the guide into every PDB in the PDB",
      ],
      answer: 0,
      explanation: "Off-target triage is a genomic alignment / mismatch problem first; chemistry filters do not apply to gRNA sequences.",
    },
    {
      topic: "Expression QC",
      question: "Before ranking targets by disease vs normal expression, a critical QC step is:",
      choices: [
        "Check library size, batch effects, and that disease labels are not confounded with sequencing center",
        "Sort genes alphabetically and take the first 50",
        "Convert all TPMs to InChIKeys",
        "Drop any gene with a known crystal structure",
      ],
      answer: 0,
      explanation: "Batch and label confounding create false differential expression — standard omics hygiene before target ranking.",
    },
    {
      topic: "Reference genomes",
      question: "Why pin a reference genome build (e.g. GRCh38) in a genomics pipeline config?",
      choices: [
        "Coordinates and annotations are build-specific; mixing builds silently breaks variant and peak joins",
        "Genome builds only affect plot colors",
        "NCBI rejects any pinned build",
        "BioPython cannot read FASTA unless the build changes daily",
      ],
      answer: 0,
      explanation: "Lift-over or rebuild is required when mixing assemblies — pinning prevents silent coordinate mismatches.",
    },
  ],

  chemistry: [
    {
      topic: "Cheminformatics · SMILES",
      question: "In a hit-list export from a virtual screen, what does a SMILES string primarily encode?",
      choices: [
        "A linear text representation of a molecular graph (atoms & bonds)",
        "A 3D conformer coordinate dump",
        "A protein secondary-structure string",
        "A hashed binary fingerprint only",
      ],
      answer: 0,
      explanation: "SMILES encodes atoms and bonds as text. 3D coords need SDF/MOL2; fingerprints are derived descriptors, not SMILES itself.",
    },
    {
      topic: "Identifiers · InChIKey",
      question: "Why do compound registries often store InChIKey alongside SMILES in pharma warehouses?",
      choices: [
        "InChIKey is a fixed-length hash-like key useful for deduplication across tautomer/SMILES variants",
        "InChIKey stores 3D docking poses",
        "InChIKey replaces the need for any structural format",
        "InChIKey is only valid for peptides",
      ],
      answer: 0,
      explanation: "InChIKey provides a compact, standardized lookup key. Canonical SMILES still varies by toolkit; InChI/InChIKey improve identity matching.",
    },
    {
      topic: "Formats · SDF",
      question: "A vendor library arrives as multi-molecule SDF. What does each molfile block typically contain?",
      choices: [
        "Connection table (atoms/bonds) plus optional properties like vendor ID or MW",
        "Only protein FASTA headers",
        "RNA-seq count matrices",
        "BLAST pairwise alignments",
      ],
      answer: 0,
      explanation: "SDF concatenates molfiles with optional SD tags — the workhorse format for small-molecule libraries in discovery.",
    },
    {
      topic: "RDKit · molecules",
      question: "In a triage notebook, which RDKit call parses a SMILES into a molecule object for descriptor calc?",
      code: "from rdkit import Chem",
      choices: [
        "Chem.MolFromSmiles(smi)",
        "Chem.ParseSMILES(smi)",
        "Chem.SmilesToMol(smi)",
        "Chem.ReadSmiles(smi)",
      ],
      answer: 0,
      explanation: "Chem.MolFromSmiles is the canonical constructor; it returns None on invalid SMILES — always null-check in pipelines.",
    },
    {
      topic: "RDKit · fingerprints",
      question: "For a Tanimoto nearest-neighbor search on a corporate compound collection, which fingerprint is a common default?",
      choices: [
        "Morgan (ECFP-like) fingerprints via AllChem.GetMorganFingerprintAsBitVect",
        "Only raw SMILES string distance",
        "PWM matrices from Bio.motifs",
        "FASTA k-mer counts",
      ],
      answer: 0,
      explanation: "Morgan/ECFP bit vectors plus Tanimoto similarity are the workhorse for ligand-based neighbor finding in medchem.",
    },
    {
      topic: "ADMET filters",
      question: "Applying a Lipinski-inspired filter in RDKit, which property set is most associated with oral drug-likeness rules of thumb?",
      choices: [
        "MW, LogP, H-bond donors/acceptors (and often rotatable bonds)",
        "Only melting point and color",
        "FASTA length and GC%",
        "BLAST e-value only",
      ],
      answer: 0,
      explanation: "Ro5-style filters use MW, LogP, HBD/HBA (Veber adds TPSA/rotors). They are heuristics, not hard go/no-go in modern discovery.",
    },
    {
      topic: "ChEMBL-style data",
      question: "Joining bioactivity to structures, you see standard_type = 'IC50' and standard_units = 'nM'. What should you do before QSAR?",
      choices: [
        "Harmonize units, handle censored/qualified values, and deduplicate by parent compound",
        "Train directly on mixed M and nM without conversion",
        "Drop all IC50 and keep only %inhibition at one conc",
        "Convert IC50 to SMILES length as the label",
      ],
      answer: 0,
      explanation: "Activity curation — unit conversion, qualifier handling (>, <), salt/parent mapping — dominates real ChEMBL-derived QSAR quality.",
    },
    {
      topic: "Descriptors · QSAR",
      question: "You engineer features for a random-forest pIC50 model. Which set is typical for classical ligand-based QSAR?",
      choices: [
        "Physicochemical descriptors + fingerprints (e.g. Morgan bits, LogP, TPSA, MW)",
        "Only raw PDB ATOM lines as strings",
        "RNA-seq TPM vectors for the ligand",
        "Keyboard scan codes of the SMILES characters",
      ],
      answer: 0,
      explanation: "Classical QSAR combines continuous descriptors with binary fingerprints; structure-based models may add pocket features separately.",
    },
    {
      topic: "RDKit · sanitization",
      question: "MolFromSmiles returns a molecule but later descriptor calc fails. What is a common root cause?",
      choices: [
        "Failed or incomplete sanitization / valence issues; need sanitization checks or cleanup",
        "SMILES are never usable in RDKit",
        "You must convert SMILES to FASTA first",
        "RDKit only reads InChIKey",
      ],
      answer: 0,
      explanation: "Sanitization enforces valence and aromaticity. Broken vendor SMILES often need cleanup (SanitizeMol, salt stripping).",
    },
    {
      topic: "Substructure filters",
      question: "Flagging PAINS-like alerts on a hit list in RDKit is typically done with:",
      choices: [
        "SMARTS-based structural filters (e.g. FilterCatalog / custom SMARTS)",
        "BLASTP against UniProt",
        "GC content thresholds",
        "Entrez taxonomy IDs",
      ],
      answer: 0,
      explanation: "Substructure alerts use SMARTS patterns. They are triage aids — not definitive proof of assay interference.",
    },
    {
      topic: "Molecular graphs · GNNs",
      question: "In a graph neural net for binding prediction, what are the natural node and edge features?",
      choices: [
        "Atoms as nodes (element, charge, hybridization…) and bonds as edges (order, conjugation…)",
        "SMILES characters as CNN tokens only — graphs are unused",
        "PDB residue indices as SMILES nodes",
        "Plate well IDs as graph edges",
      ],
      answer: 0,
      explanation: "Message-passing GNNs operate on molecular graphs: atom nodes and bond edges, optionally with 3D distances for spatial models.",
    },
    {
      topic: "Generative chemistry",
      question: "A SMILES VAE proposes invalid strings. Which mitigation is most appropriate in production ideation?",
      choices: [
        "Use grammar/atom-aware decoders or graph generators, plus RDKit validity & property filters post hoc",
        "Accept all outputs and skip chemistry checks",
        "Convert invalid SMILES to protein FASTA",
        "Train only on InChIKey characters",
      ],
      answer: 0,
      explanation: "Validity constraints (syntax models, graph decoders) plus chemistry filters (valence, PAINS, property windows) are standard.",
    },
  ],

  molecular: [
    {
      topic: "Structures · PDB",
      question: "You download a kinase co-crystal for pose inspection. Which BioPython module parses PDB coordinate records?",
      choices: [
        "Bio.PDB",
        "Bio.StructureIO",
        "Bio.Align.PDB",
        "Bio.SeqIO with format='pdb'",
      ],
      answer: 0,
      explanation: "Bio.PDB (PDBParser / MMCIFParser) builds Structure→Model→Chain→Residue→Atom hierarchies for structural biology work.",
    },
    {
      topic: "Bio.PDB · neighbors",
      question: "Measuring ligand–pocket contacts, which Bio.PDB pattern finds atoms within a distance cutoff?",
      choices: [
        "NeighborSearch(atom_list).search(center, radius)",
        "PDBParser.nearby(ligand, 5)",
        "SeqIO.proximity()",
        "Align.Structure.contacts()",
      ],
      answer: 0,
      explanation: "Bio.PDB.NeighborSearch builds a KD-tree over atoms for efficient spatial queries around ligands or residues.",
    },
    {
      topic: "Protein language models",
      question: "Embedding a target sequence with a protein LM (e.g. ESM-style) for druggability features — what is a valid use?",
      choices: [
        "Sequence embeddings as features for variant effect, binding, or tractability models alongside structure cues",
        "Replacing all chemical structures with DNA barcodes only",
        "Generating valid small-molecule SMILES directly from DNA codons without a decoder",
        "Computing Tanimoto similarity between proteins",
      ],
      answer: 0,
      explanation: "pLMs yield contextual sequence embeddings used in variant effect and multimodal target/ligand models — not SMILES generators by themselves.",
    },
    {
      topic: "Multi-omics · targets",
      question: "Prioritizing targets for an AI-first portfolio, which integration is most coherent?",
      choices: [
        "Genetics/omics evidence + tractability (structure, assays) + competitive landscape features in one ranked model",
        "Only social media mentions of the gene symbol",
        "Random genes with the shortest FASTA files",
        "Targets with no human ortholog exclusively",
      ],
      answer: 0,
      explanation: "Target ID combines causal human genetics, expression, safety, and chemical tractability — CompBio engineering stitches these evidence layers.",
    },
    {
      topic: "mmCIF vs PDB",
      question: "For large ribosome or antibody structures, why prefer mmCIF parsers over legacy PDB text?",
      choices: [
        "mmCIF scales past PDB column limits and is the modern wwPDB primary format",
        "PDB text supports infinite chains; mmCIF does not",
        "Bio.PDB cannot read mmCIF at all",
        "mmCIF stores only SMILES",
      ],
      answer: 0,
      explanation: "Legacy PDB fixed columns break on large asymmetric units; MMCIFParser is preferred for modern deposits.",
    },
    {
      topic: "Pocket detection",
      question: "Before docking a new chemotype, you need putative binding sites on an apo structure. A typical Python approach is:",
      choices: [
        "Geometric/energetic pocket finders (or known orthosteric site from homologs) then box definition",
        "Using the longest surface loop as the only site always",
        "Random 5Å cubes scattered in solvent only",
        "BLAST of the ligand SMILES against UniProt",
      ],
      answer: 0,
      explanation: "Site definition drives docking success — pocket tools or homology-mapped sites beat arbitrary boxes.",
    },
    {
      topic: "AlphaFold models",
      question: "Using an AlphaFold model for structure-based design, what caveat should your pipeline encode?",
      choices: [
        "Check pLDDT/PAE confidence, especially in loops and interfaces, before trusting pocket geometry",
        "pLDDT is irrelevant if the FASTA header looks clean",
        "AF models always include co-crystallized clinical ligands",
        "Confidence metrics only apply to DNA structures",
      ],
      answer: 0,
      explanation: "Low-confidence regions mislead pocket and docking workflows — confidence filters belong in CompBio QC.",
    },
    {
      topic: "Multimodal fusion",
      question: "A complex model fuses ligand graphs, pocket voxels, and assay metadata. What failure mode should you test first?",
      choices: [
        "Modality dropout / missing pocket structures and assay-type shift — ensure graceful degradation",
        "Whether the GPU brand matches the laptop sticker",
        "If FASTA headers contain emoji",
        "Sorting SMILES alphabetically before every epoch only",
      ],
      answer: 0,
      explanation: "Real discovery data is incomplete: apo structures, missing assays, new target families. Robust fusion handles missing modalities.",
    },
    {
      topic: "Interface mutations",
      question: "Scoring alanine scanning on a PPI interface for biologics tractability typically needs:",
      choices: [
        "Structure-aware energy or ML models on the complex, not sequence alone",
        "Only GC% of the encoding DNA",
        "Tanimoto on the antibody SMILES string only",
        "Plate map well letters",
      ],
      answer: 0,
      explanation: "Hot-spot prediction is structural/energetic; sequence-only GC or ligand fingerprints miss the interface physics.",
    },
    {
      topic: "Selectivity structural",
      question: "Explaining kinase selectivity cliffs with structures, a useful CompBio artifact is:",
      choices: [
        "Aligned binding-site residues / interaction maps across off-target structures",
        "Alphabetical sort of kinase gene symbols only",
        "Average SMILES length per kinase family",
        "RNA-seq batch barcodes",
      ],
      answer: 0,
      explanation: "Residue-level pocket comparisons connect SAR selectivity to structural determinants.",
    },
    {
      topic: "Water / cofactors",
      question: "Preparing a holo PDB for modeling, why might you retain crystallographic waters or cofactors selectively?",
      choices: [
        "Bridging waters and cofactors can define recognition; blanket deletion can distort the site",
        "All heteroatoms must always be deleted for Bio.PDB to parse",
        "Waters are stored as SMILES and break parsers",
        "Cofactors are never biologically relevant",
      ],
      answer: 0,
      explanation: "Thoughtful heteroatom handling is part of structure prep — not automatic strip-everything.",
    },
    {
      topic: "Domain boundaries",
      question: "Expressing a soluble kinase domain for assays, CompBio support often includes:",
      choices: [
        "Domain annotation (Pfam/UniProt) plus disorder/pLDDT to propose construct boundaries",
        "Picking random 50-aa windows from the FASTA",
        "Using the full chromosome sequence as the expression construct",
        "Maximizing transmembrane helices in the construct",
      ],
      answer: 0,
      explanation: "Construct design uses domain and disorder evidence to improve expressibility and structural integrity.",
    },
  ],

  biologics: [
    {
      topic: "BioPython · translation",
      question: "Translating a coding sequence for an antibody Fv domain, which call yields an amino-acid Seq?",
      code: "from Bio.Seq import Seq\ncds = Seq('ATGGAAGTGCAG...')",
      choices: [
        "cds.translate()",
        "cds.transcribe().protein()",
        "SeqIO.translate(cds)",
        "cds.to_protein(table=1)",
      ],
      answer: 0,
      explanation: "Seq.translate() maps DNA/RNA codons to amino acids (optional codon table). Transcription alone does not produce protein.",
    },
    {
      topic: "BioPython · Align",
      question: "You align ortholog catalytic sites before homology modeling. Which Bio.Align approach fits pairwise protein alignment?",
      choices: [
        "PairwiseAligner with a protein substitution matrix (e.g. BLOSUM62)",
        "SeqIO.align() with format='clustal'",
        "Entrez.align_blast_only",
        "PDBParser.align_chains()",
      ],
      answer: 0,
      explanation: "Bio.Align.PairwiseAligner (replacing deprecated pairwise2) supports protein matrices for ortholog comparisons.",
    },
    {
      topic: "CDR annotation",
      question: "Numbering antibody variable domains (Kabat/IMGT/Chothia) in a Python pipeline is important because:",
      choices: [
        "CDR boundaries depend on the numbering scheme — critical for humanization and liability scans",
        "All schemes place CDRs at identical residue indices always",
        "Numbering only matters for small-molecule SMILES",
        "BioPython forbids storing antibody sequences",
      ],
      answer: 0,
      explanation: "Scheme choice shifts CDR definitions; downstream developability and grafting depend on consistent numbering.",
    },
    {
      topic: "Developability",
      question: "Flagging antibody sequence liabilities (deamidation, isomerization, oxidation motifs) is typically:",
      choices: [
        "Motif/rule scans on AA sequence plus structure context when available",
        "Lipinski Ro5 on the IgG SMILES only",
        "GC% of the constant region alone",
        "Docking Fc to every metabolite",
      ],
      answer: 0,
      explanation: "Sequence motifs (NG, DG, Met oxidation, etc.) drive early developability flags; chemistry Ro5 is for small molecules.",
    },
    {
      topic: "Humanization",
      question: "When humanizing a murine mAb, CompBio usually compares:",
      choices: [
        "Framework homology to human germline V-genes while preserving CDR structural integrity",
        "Only the murine constant-region DNA GC content",
        "Tanimoto similarity of heavy-chain SMILES to caffeine",
        "Plate well positions from the hybridoma screen",
      ],
      answer: 0,
      explanation: "Humanization balances human framework identity against CDR loop conformation and binding.",
    },
    {
      topic: "PTMs",
      question: "Predicting N-linked glycosylation risk on a therapeutic protein sequence relies on:",
      choices: [
        "Sequon detection (e.g. N-X-S/T, X≠P) with structural accessibility when possible",
        "Counting cysteines only",
        "BLAST against ChEMBL compounds",
        "Converting the protein to Morgan fingerprints",
      ],
      answer: 0,
      explanation: "N-X-S/T sequons are the classic sequence signal; 3D accessibility refines which sites are occupied.",
    },
    {
      topic: "Chain pairing",
      question: "From a single-cell V(D)J export, recovering IgG binders requires:",
      choices: [
        "Correct heavy–light pairing per cell barcode before translating and annotating CDRs",
        "Randomly pairing any heavy with any light in the run",
        "Ignoring light chains because binding is heavy-only always",
        "Storing only nucleotide lengths without sequences",
      ],
      answer: 0,
      explanation: "True cognate pairing is required to reconstitute the binder; random H–L pairs invent false antibodies.",
    },
    {
      topic: "Isoelectric point",
      question: "Estimating pI for a mAb construct in Python is commonly used to:",
      choices: [
        "Anticipate viscosity/clearance risks and guide buffer/formulation hypotheses",
        "Replace the need for any binding assay",
        "Compute docking scores directly",
        "Generate SMILES for the Fc glycan only",
      ],
      answer: 0,
      explanation: "Sequence-derived pI is a developability and formulation signal — not a potency substitute.",
    },
    {
      topic: "Ortholog cross-reactivity",
      question: "Before tox species selection, you compare epitope conservation across orthologs. Best practice is:",
      choices: [
        "Align ortholog sequences/structures at the epitope and flag non-conservative substitutions",
        "Assume 100% cross-reactivity if gene symbols match",
        "Use only codon usage tables",
        "Compare InChIKeys of the antibodies",
      ],
      answer: 0,
      explanation: "Epitope-level ortholog differences drive species cross-reactivity — gene name equality is insufficient.",
    },
    {
      topic: "Expression constructs",
      question: "Designing a scFv from VH/VL sequences in code typically includes:",
      choices: [
        "Choosing linker length/composition and orientation (VH–linker–VL vs reverse) with liability checks",
        "Concatenating without a linker because domains never clash",
        "Inserting random STOP codons between domains",
        "Replacing CDRs with poly-Gly always",
      ],
      answer: 0,
      explanation: "Linker and orientation affect folding and aggregation — explicit design beats naive concatenation.",
    },
    {
      topic: "Allotype / immunogenicity",
      question: "In therapeutic antibody reporting, why track human allotypes and foreign epitopes?",
      choices: [
        "They inform immunogenicity risk and clinical ADA monitoring strategy",
        "They determine Morgan fingerprint radius",
        "They are required only for small-molecule IND filings",
        "They replace potency measurements",
      ],
      answer: 0,
      explanation: "Allotype and T-cell epitope flags feed immunogenicity risk discussions in biologics development.",
    },
    {
      topic: "Stability predictors",
      question: "Combining sequence and structure for mAb stability ML, a sensible feature set includes:",
      choices: [
        "CDR/framework composition, net charge patches, SASA, and known liability motifs",
        "Only the filename of the FASTA",
        "Vendor catalog prices",
        "Keyboard latency while typing the sequence",
      ],
      answer: 0,
      explanation: "Developability models use biophysical and motif features grounded in antibody engineering practice.",
    },
  ],

  docking: [
    {
      topic: "Docking post-processing",
      question: "After a large docking campaign, scores alone rank poorly vs experiment. A robust Python triage often includes:",
      choices: [
        "Pose clustering, interaction fingerprints, rescoring/ML, and visual/pharmacophore filters",
        "Sorting solely by alphabetical ligand name",
        "Keeping only the worst energy pose",
        "Converting poses to RNA-seq counts",
      ],
      answer: 0,
      explanation: "Docking enrichment improves with consensus rescoring, IFPs, and human-in-the-loop pose QC — not raw score alone.",
    },
    {
      topic: "3D · conformers",
      question: "For shape or pharmacophore screening in Python, which RDKit capability is commonly used first?",
      choices: [
        "EmbedMolecule / ETKDG conformer generation then align or shape overlay",
        "Seq.translate on the SMILES string",
        "Entrez.efetch of conformers",
        "FASTA MSA of ligands",
      ],
      answer: 0,
      explanation: "ETKDG conformer generation underpins 3D descriptors, shape sims, and pharmacophore workflows before heavier MD/docking.",
    },
    {
      topic: "Grid box",
      question: "Defining a docking search box for a kinase ATP site should primarily be based on:",
      choices: [
        "Known ligand/cofactor coordinates or a validated pocket center with adequate padding",
        "The geometric center of the entire asymmetric unit always",
        "Random chromosome coordinates",
        "The first ATOM line in the file regardless of chain",
      ],
      answer: 0,
      explanation: "Box placement follows the binding site of interest — whole-structure centroids waste sampling.",
    },
    {
      topic: "Pose clustering",
      question: "Why cluster docking poses before picking representatives for medchem review?",
      choices: [
        "Redundant near-identical poses inflate hit lists; cluster centroids diversify binding modes",
        "Clustering converts proteins into SMILES",
        "Only the densest cluster is ever chemically valid",
        "Clustering replaces the need for a receptor structure",
      ],
      answer: 0,
      explanation: "RMSD clustering compresses pose ensembles into distinct modes for human and IFP triage.",
    },
    {
      topic: "Interaction fingerprints",
      question: "Interaction fingerprints (IFPs) after docking are useful because they:",
      choices: [
        "Encode which residues/contacts are made, enabling similarity to known actives and filter rules",
        "Replace the protein with a fingerprint of the solvent only",
        "Are identical to Morgan fingerprints of the ligand alone",
        "Cannot be computed in Python",
      ],
      answer: 0,
      explanation: "IFPs capture pose-specific contacts — complementary to ligand-only fingerprints.",
    },
    {
      topic: "Protonation",
      question: "Before docking, ligand and pocket protonation/tautomer states matter because:",
      choices: [
        "Wrong protomers change H-bond patterns and ranking; pH-aware prep is standard",
        "Protonation never affects scoring functions",
        "All ligands must be deprotonated to carbon-only graphs",
        "Bio.PDB automatically docks protomers",
      ],
      answer: 0,
      explanation: "Tautomer/protomer enumeration at assay pH is part of credible structure-based pipelines.",
    },
    {
      topic: "Consensus docking",
      question: "Running multiple docking engines/scoring functions helps when:",
      choices: [
        "You want consensus enrichment and to reduce engine-specific pose bias",
        "You need to avoid looking at any structure",
        "SMILES validity checks fail",
        "RNA-seq QC is the bottleneck",
      ],
      answer: 0,
      explanation: "Consensus and orthogonal rescoring are common remedies for single-engine failure modes.",
    },
    {
      topic: "Induced fit",
      question: "Rigid receptor docking misses actives on a flexible loop-gated pocket. A CompBio response is:",
      choices: [
        "Ensemble docking against multiple conformers/MD frames or induced-fit protocols",
        "Deleting the loop from the FASTA and redocking",
        "Switching all scores to GC%",
        "Using only 1D fingerprints forever",
      ],
      answer: 0,
      explanation: "Receptor flexibility is handled via ensembles, soft docking, or induced-fit — not ignoring the loop.",
    },
    {
      topic: "Covalent docking",
      question: "For a cysteine-targeting covalent warhead library, docking setup should include:",
      choices: [
        "Reactive residue definition and covalent constraints / warhead-aware protocols",
        "Standard noncovalent docking with warheads deleted",
        "Treating the covalent bond as a SMILES wildcard only in the protein FASTA",
        "Ignoring geometry around the nucleophile",
      ],
      answer: 0,
      explanation: "Covalent programs constrain attachment geometry to the nucleophilic residue — essential for warhead series.",
    },
    {
      topic: "Enrichment metrics",
      question: "Reporting docking virtual-screen quality to stakeholders, a standard metric is:",
      choices: [
        "Early enrichment / EF / ROC-AUC on known actives vs decoys (with caveats)",
        "Average filename length of pose PDBs",
        "Number of CPU cores only",
        "Alphabetical recall of ligand vendors",
      ],
      answer: 0,
      explanation: "Enrichment factors and ROC-style metrics (with decoy bias caveats) communicate VS performance.",
    },
    {
      topic: "Clash / strain",
      question: "A top-scoring pose shows severe ligand strain and steric clashes. You should:",
      choices: [
        "Filter by strain/clash scores and inspect physically plausible poses before synthesis proposals",
        "Synthesize immediately because score overrides physics",
        "Convert the pose to RNA and translate",
        "Average it with the worst pose",
      ],
      answer: 0,
      explanation: "Unphysical poses are a known docking failure mode — strain and clash filters protect medchem time.",
    },
    {
      topic: "Water-mediated H-bonds",
      question: "When a crystal pose relies on bridging waters, docking without waters may:",
      choices: [
        "Miss key recognition; consider explicit waters, displaceable water predictions, or pharmacophore constraints",
        "Always improve enrichment automatically",
        "Convert the receptor into a peptide SMILES",
        "Be required by Bio.Entrez",
      ],
      answer: 0,
      explanation: "Bridging waters can be part of the pharmacophore — omitting them changes the interaction pattern.",
    },
  ],

  clinical: [
    {
      topic: "Assay data · pandas",
      question: "An HTS plate map CSV has columns compound_id, well, and IC50_nM. Which pandas pattern best loads it for QC?",
      choices: [
        "pd.read_csv('plate.csv') then filter/astype numeric IC50",
        "open('plate.csv').readlines() and split on commas only",
        "np.loadtxt('plate.csv') ignoring headers",
        "json.load(open('plate.csv'))",
      ],
      answer: 0,
      explanation: "pd.read_csv handles headers, mixed types, and missing wells. IC50 should be coerced numeric before thresholding actives.",
    },
    {
      topic: "Units · potency",
      question: "An assay table lists pIC50 = 7.0. Approximately what IC50 does that correspond to?",
      choices: [
        "100 nM (IC50 = 10^(-pIC50) M)",
        "7 μM exactly",
        "0.7 M",
        "70 mM",
      ],
      answer: 0,
      explanation: "pIC50 = −log10(IC50[M]). pIC50 7 ⇒ 10⁻⁷ M = 100 nM — common potency reporting in SAR tables.",
    },
    {
      topic: "Assay pipelines",
      question: "Plate-based IC50 curves are fit per compound. Which practice avoids leaking future dose points into a potency model?",
      choices: [
        "Split by compound scaffold/series (or time) so all concentrations of a molecule stay in one fold",
        "Randomly shuffle every well row independently into train/test",
        "Put all high-dose wells in train and low-dose in test",
        "Use the same compounds in train and test if doses differ",
      ],
      answer: 0,
      explanation: "Group-aware splits (scaffold / Bemis–Murcko / temporal) prevent over-optimistic QSAR from near-duplicate chemotypes.",
    },
    {
      topic: "Target engagement",
      question: "You merge cellular IC50 with biochemical Ki. Why can naive pooling mislead a potency model?",
      choices: [
        "Different assay modalities, protein forms, and conditions are not commensurate without careful normalization",
        "Ki and IC50 are always identical by definition",
        "Cellular assays never use nM units",
        "Biochemical assays cannot be stored in pandas",
      ],
      answer: 0,
      explanation: "Cross-assay pooling needs metadata-aware modeling; Cheng–Prusoff and cell permeability confound direct IC50↔Ki merges.",
    },
    {
      topic: "Train/test leakage",
      question: "Your GNN hits 0.98 AUROC on a random split of ChEMBL kinase IC50s but fails prospectively. Most likely cause?",
      choices: [
        "Analogue / scaffold leakage — chemically similar molecules in both splits inflate metrics",
        "AUROC cannot be used for potency tasks ever",
        "RDKit fingerprints are incompatible with neural nets",
        "Too much protein sequence data was included",
      ],
      answer: 0,
      explanation: "Scaffold and time splits expose generalization; random splits leak close analogues and overstate discovery performance.",
    },
    {
      topic: "Uncertainty",
      question: "For active learning on expensive wet-lab assays, what should the acquisition function balance?",
      choices: [
        "Predicted potency / utility vs epistemic uncertainty (explore–exploit)",
        "Only molecules with the longest SMILES",
        "Compounds already measured 10+ times",
        "Random plates without model input",
      ],
      answer: 0,
      explanation: "Bayesian / ensemble uncertainty guides which compounds to synthesize or assay next under budget constraints.",
    },
    {
      topic: "Conformal / calibration",
      question: "Medicinal chemists ask for prediction intervals on pIC50. What is a sound approach?",
      choices: [
        "Calibrated uncertainty (e.g. ensembles, conformal prediction) validated on scaffold-held-out series",
        "Always report ±0.01 regardless of domain",
        "Hide errors when confidence is low",
        "Use training RMSE as the interval for every new chemotype",
      ],
      answer: 0,
      explanation: "Well-calibrated uncertainties — especially under scaffold shift — are more decision-useful than point estimates alone.",
    },
    {
      topic: "PK / exposure",
      question: "Linking in vitro potency to expected clinical dose requires which additional concepts?",
      choices: [
        "Clearance, bioavailability, plasma binding, and free-drug hypotheses — not IC50 alone",
        "Only the molecular weight cubed",
        "FASTA length of the target",
        "Number of docking poses kept",
      ],
      answer: 0,
      explanation: "Translational pharmacology connects potency to exposure; IC50 without PK is not a dose.",
    },
    {
      topic: "Biomarkers",
      question: "For a precision oncology trial hypothesis, CompBio support often includes:",
      choices: [
        "Patient stratification features (genomics/expression) linked to target pathway activity and response labels",
        "Only vendor catalog IDs of lab plastics",
        "Randomizing biomarker labels after unblinding",
        "Replacing endpoints with SMILES strings",
      ],
      answer: 0,
      explanation: "Biomarker pipelines join molecular features to clinical response under proper labels and leakage controls.",
    },
    {
      topic: "Safety signals",
      question: "Triaging secondary pharmacology / safety panel results in Python, you should:",
      choices: [
        "Normalize assay units, flag potent off-targets, and join to therapeutic index vs on-target potency",
        "Average all off-target IC50s into one SMILES",
        "Delete any off-target weaker than 1 M without review",
        "Treat safety panels as genomics FASTA",
      ],
      answer: 0,
      explanation: "Safety triage is comparative (on- vs off-target) with unit-aware tables — not ad-hoc deletion.",
    },
    {
      topic: "Real-world evidence",
      question: "Exploring RWE for indication expansion, a major analytical risk is:",
      choices: [
        "Confounding and selection bias — needs careful cohorts, not naive correlations",
        "Too many crystal structures",
        "Excessive RDKit sanitization",
        "Overuse of BLOSUM62",
      ],
      answer: 0,
      explanation: "Observational clinical data mislead without causal/cohort discipline — a core translational CompBio concern.",
    },
    {
      topic: "Federated / privacy",
      question: "Two pharma partners want to train a shared ADMET model without sharing structures. A CompBio-aware option is:",
      choices: [
        "Federated learning or sharing only fingerprints/embeddings under a legal data contract — never raw IP SMILES by default",
        "Emailing full SDF libraries to a public GitHub gist",
        "Publishing all series in a blog post",
        "Training only on public caffeine SMILES",
      ],
      answer: 0,
      explanation: "IP-sensitive structures drive federated or feature-level collaboration patterns with strict governance.",
    },
  ],
};

const SESSION_SIZE = 10;

/** Back-compat alias if older snippets reference LEVELS */
const LEVELS = DOMAINS;
